server:
  port: 9191

spring:
  application:
    name: payment-service
  h2:
    console:
      enabled: true
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
