server :
 port : 9192

spring :
 h2 :
  console :
   enabled : true 
 application : 
  name : order-service  
 cloud :
  compatibility-verifier :
   enabled : false
   
eureka : 
 client : 
  enabled: false
  register-with-eureka : true
  fetch-registry : true
  service-url :
   defaultZone : http://localhost:8761/eureka/
 instance : 
  hostname : localhost     
   
 
 

